### ISSUE TITLE
Conversion issue with sensor

### ISSUE THREAD

**Issue by lightmaster** [briis/mbweather#5]
The temperature sensors are showing Celsius numbers, while showing the F temp symbol. Being the the US, it should be converting the Celsius to Fahrenheit.  Correct current temp is 52F.

Rain seems correct, Wind unknown since its been 0 since I've installed the integration. Will update whenever it shows a wind speed.

While fixing this, can you add the option to pick and choose which units you use for everything?

Thanks

![mbweather image](https://i.postimg.cc/v8Fft2Bk/mbweather-conversion-issues.png)

**Comment by briis** [comment]
Hi @lightmaster 
The temperature bug should now be resolved, and I have pushed a new release, that will show up in HACS soon.
With regards to the ability to specify Units for each type of sensor, that will take a bit longer, as this will need some significant code change in the Meteobridge Wrapper. I am just about to move house, so I will close down my systems for a little while, but once I am up and running again, I will start working on that. I will open a separate issue for that.

**Comment by lightmaster** [comment]
Is there some trick to getting it updated through HACS? I clicked update, then restarted HA. Still shows as 6.7F right now without the Fahrenheit to Celsius conversion. Also checked in the States tab of Developer Tools: state = 6.7, unit of measure = F.

**Comment by briis** [comment]
If you click on Meteobridge Weather in HACS, does it say Version 1.2.2 as installed version?

**Comment by lightmaster** [comment]
Says Version 1.2.2 last updated 12 hours ago.
![version](https://i.postimg.cc/ZTVHTC3f/Screenshot-20200215-133501-Home-Assistant.jpg)

Shows 17F currently.
![HA MBWeather](https://i.postimg.cc/9WW15G4R/Screenshot-20200215-133511-Home-Assistant.jpg)

Current weather
![MB-HWS Weather](https://i.postimg.cc/cxCm60Bd/Screenshot-20200215-133545-Chrome-Beta.jpg)

Other numbers like Wind and Pressure look correct.

**Comment by briis** [comment]
This is really strange. I cannot reproduce this - when I select Imperial as unit system in HA I get the temperature values in F and vice versa.
Just to check what the value is that we are converting, could you try and run this in a browser, replacing [PASSWORD] with your meteobridge password and [IP ADRESS] with the local Meteobridge IP Address:

`http://meteobridge:[PASSWORD]@[IP address]/cgi-bin/template.cgi?template=[th0temp-act:0]` 

Does this output the current outdoor temperature in F or C?

Also, could you try and remove the installation from your system, restart HA, and then re-install. Just to make sure you have all the latest files.

**Comment by lightmaster** [comment]
Calling that template manually gets me the temp in celcius. About to try removing and reinstalling it from HA.

**Comment by lightmaster** [comment]
That got it, looks like HACS didn't update the changed file.

**Comment by briis** [comment]
Perfect. I had read somewhere else that there has been some problems with HACS. 
I will look in to the Unit Specifications as soon as I have time.
